### ISSUE TITLE
changing environment gives error

### ISSUE THREAD

**Issue by MuhammadSaim2011** [vstark21/RL_gym#2]
Hello Sir,

I ran your algorithms and it works fine and generate the expected results. but whenever I change environments it gives me an error.
e.g with DDQN implementation whenever I change environment from "CartPole-v0" to "Pendulum-v0" error comes as 
**keras.layers.Dense(self.env.action_space.n, activation="linear")
AttributeError: 'Box' object has no attribute 'n'**. looking forward to hearing from you and an advice on how to test the same algorithms on different environments
Best Regards

**Comment by vstark21** [comment]
Hello @MuhammadSaim2011,
Some of the algorithms in this implementations will work only in environments with discrete action space and some will work only in environments with continuous action space. As, DDQN implementation will work on environments with discrete action space,
it doesn't work in `Pendulum-v0`

**Comment by MuhammadSaim2011** [comment]
> Hello @MuhammadSaim2011,
> Some of the algorithms in this implementations will work only in environments with discrete action space and some will work only in environments with continuous action space. As, DDQN implementation will work on environments with discrete action space,
> it doesn't work in `Pendulum-v0`

Thanks a lot for your timely response
